Adds sorting for this current week. No python 3 support
TypeError: unorderable types: dict() < dict() error occurs when
using python3 because of the way dictionaries are ordered. Just going
to use python2 for now. I'll work it out later.